apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: listener
spec:
  triggers:
    - bindings:
        - ref: tekton-triggers-binding
      template:
        ref: template
      interceptors:
      - ref:
          name: "gitlab"
          kind: ClusterInterceptor
        params:
        - name: "secretRef"
          value:
            secretName: gitlab-webhook
            secretKey: secretkey
        - name: "eventTypes"
          value: ["Push Hook"]
