apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: template
spec:
  params:
    - name: appname
  resourcetemplates:
    - apiVersion: tekton.dev/v1
      kind: PipelineRun
      metadata:
        generateName: pipelinerun-demo-
        labels:
          tekton.dev/pipeline: pipeline-demo
      spec:
        params:
          - name: target-app-path
            value: $(tt.params.appname)
          - name: git-app-url
            value: 'https://gitlab.com/yono1/cps-demo'
          - name: git-app-revision
            value: main
          - name: git-manifests-url
            value: 'https://gitlab.com/yono1/cps-demo-manifests'
          - name: git-manifests-revision
            value: main
          - name: container-registry-project
            value: cps-demo
          - name: container-registry-url
            value: 'registry.gitlab.com/yono1'
          - name: container-image-name
            value: $(tt.params.appname)
          - name: container-image-version
            value: v1
        pipelineRef:
          name: pipeline-demo
        taskRunTemplate:
          serviceAccountName: pipeline
        timeouts:
          pipeline: 1h0m0s
        workspaces:
          - name: app-workspace
            persistentVolumeClaim:
              claimName: app-workspace
          - name: manifests-workspace
            persistentVolumeClaim:
              claimName: manifests-workspace
          - name: temp-dir
            persistentVolumeClaim:
              claimName: tempdir