loggingColor=true
loggingJson=false
camel.main.modeline=true
camel.jbang.compileWorkDir=.camel-jbang/compile
camel.jbang.health=false
camel.jbang.metrics=false
camel.jbang.console=false
camel.jbang.verbose=false
camel.jbang.camel-version=4.11.0
camel.jbang.springBootVersion=3.4.3
camel.jbang.quarkusVersion=3.19.3
camel.jbang.quarkusGroupId=io.quarkus.platform
camel.jbang.quarkusArtifactId=quarkus-bom
camel.main.durationMaxSeconds=1
camel.jbang.kameletsVersion=4.11.0
camel.main.name=transform
camel.main.routesIncludePattern=file\:/Users/yono/Documents/work/data-mesh-demo/camel/kafka2mqtt.camel.yaml
dependency=mvn\:org.apache.camel\:camel-kamelet\:4.11.0
dependency=mvn\:org.apache.camel\:camel-yaml-dsl\:4.11.0
dependency=mvn\:org.apache.camel\:camel-core-languages\:4.11.0
dependency=mvn\:org.apache.camel\:camel-paho-mqtt5\:4.11.0
dependency=mvn\:org.apache.camel\:camel-kafka\:4.11.0
dependency=mvn\:org.apache.camel\:camel-yaml-io\:4.11.0
