apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: openshift-gitops
spec:
  destination:
    namespace: video
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      recurse: true
    path: apps/app-manifests/webapp
    repoURL: https://gitlab.com/yono1/microshift-gitops-demo.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
