apiVersion: v1
kind: Secret
metadata:
  name: github-token
  annotations:
    tekton.dev/git-0: https://github.com
type: kubernetes.io/basic-auth
stringData:
  username: ${GIT_USERNAME}
  password: ${GIT_PASSWORD}
  email: ${GIT_EMAIL}