apiVersion: v1
kind: Secret
metadata:
  name: quay-token
  annotations:
    tekton.dev/docker-0: https://quay.io
type: kubernetes.io/basic-auth
stringData:
  username: ${QUAY_USERNAME}
  password: ${QUAY_PASSWORD}