apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ovms-clusterrole
rules:
- apiGroups:
  - security.openshift.io
  resourceNames:
  - anyuid
  resources:
  - securitycontextconstraints
  verbs:
  - use