apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ovms
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ovms-clusterrole
subjects:
- kind: ServiceAccount
  name: ovms
  namespace: video