apiVersion: v1
kind: Secret
metadata:
  name: aws-config
data:
  AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
  AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
  AWS_REGION: "dummy"
  S3_ENDPOINT: $S3_ENDPOINT