kind: Service
apiVersion: v1
metadata:
  name: ovms
  labels:
    app: ovms
spec:
  type: NodePort
  ports:
    - name: 9000-tcp
      protocol: TCP
      port: 9000
      targetPort: 9000
      nodePort: 32290
  selector:
    app: ovms